// BetEdge AI — Comprehensive Mock Data
import type { Pick, Game, PlayerProp, SavedPick, Alert, User } from '../types';

export const MOCK_USER: User = {
  id: 'user_1',
  name: 'John Doe',
  email: 'john@example.com',
  subscriptionTier: 'free',
};

export const MOCK_PICKS: Pick[] = [
  // NFL picks
  {
    id: 'pick_1',
    sport: 'NFL',
    sportEmoji: '🏈',
    playerName: 'Patrick Mahomes',
    team: 'KC Chiefs',
    position: 'QB',
    statType: 'Passing Yards',
    line: 285.5,
    grade: 'A',
    confidence: 92,
    recommendation: 'OVER',
    edgeSummary: 'Strong historical edge vs. zone coverage teams.',
    gameInfo: 'Chiefs @ Ravens · 8:20 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -115 },
      { book: 'DraftKings', odds: -112, isBest: true },
      { book: 'BetMGM', odds: -118 },
      { book: 'Caesars', odds: -115 },
      { book: 'PointsBet', odds: -120 },
    ],
    keyFactors: [
      '8/10 last games OVER this line',
      'Ravens rank 28th vs. pass (338 avg allowed)',
      'Chiefs projected high game total (49.5)',
      'Mahomes averaging 312 yards in prime-time games',
    ],
    risks: [
      'Ravens may go zone to limit big plays',
      'Line has moved from 280.5 (sharp money on over)',
    ],
    trendOverCount: 8,
    trendTotal: 10,
    trendAvg: 312.4,
    aiAnalysis: 'Mahomes has cleared this line in 8 of his last 10 starts, averaging 312.4 passing yards over that span. The Ravens defense ranks 28th against the pass, surrendering 338 yards per game. With a projected game total of 49.5, the script favors a pass-heavy approach. The Chiefs have been deploying 3-WR sets at a league-high rate, creating consistent volume for Mahomes. The only concern is potential wind at M&T Bank Stadium, but forecasts show winds under 10 mph. Sharp money has pushed this line from 280.5 to 285.5, but there is still value at the current number.',
    gameId: 'game_1',
  },
  {
    id: 'pick_2',
    sport: 'NFL',
    sportEmoji: '🏈',
    playerName: 'Derrick Henry',
    team: 'BAL Ravens',
    position: 'RB',
    statType: 'Rushing Yards',
    line: 89.5,
    grade: 'B',
    confidence: 78,
    recommendation: 'OVER',
    edgeSummary: 'Favorable matchup against a bottom-10 run defense.',
    gameInfo: 'Chiefs @ Ravens · 8:20 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -110 },
      { book: 'DraftKings', odds: -108, isBest: true },
      { book: 'BetMGM', odds: -112 },
    ],
    keyFactors: [
      'Chiefs rank 26th vs. the run',
      'Henry averaging 95.3 rush yards at home',
      'Ravens favored — game script supports rushing',
    ],
    risks: [
      'Chiefs improved run D in recent weeks',
      'Potential blowout could reduce late carries',
    ],
    trendOverCount: 7,
    trendTotal: 10,
    trendAvg: 98.7,
    aiAnalysis: 'Derrick Henry has been dominant at home this season, averaging 95.3 rushing yards per game in Baltimore. The Chiefs rank 26th against the run, and with the Ravens favored by 3 points, the game script supports continued reliance on the ground game. Henry has cleared 89.5 yards in 7 of his last 10 games.',
    gameId: 'game_1',
  },
  {
    id: 'pick_3',
    sport: 'NFL',
    sportEmoji: '🏈',
    playerName: 'Tyreek Hill',
    team: 'MIA Dolphins',
    position: 'WR',
    statType: 'Receiving Yards',
    line: 78.5,
    grade: 'C',
    confidence: 62,
    recommendation: 'UNDER',
    edgeSummary: 'Tough CB matchup limits ceiling in this spot.',
    gameInfo: 'Dolphins @ Bills · 1:00 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -110 },
      { book: 'DraftKings', odds: -105, isBest: true },
      { book: 'BetMGM', odds: -115 },
    ],
    keyFactors: [
      'Bills CB Tre White expected to shadow Hill',
      'Hill 4/10 games OVER this line vs. top-5 pass D',
    ],
    risks: [
      'Hill capable of one big play changing outcome',
      'Dolphins may need to throw in negative game script',
    ],
    trendOverCount: 4,
    trendTotal: 10,
    trendAvg: 72.1,
    aiAnalysis: 'Tyreek Hill faces a tough test against Tre White, who is expected to shadow him on the outside. Against top-5 pass defenses this season, Hill has gone over 78.5 yards in just 4 of 10 games. The Bills defense has been elite at limiting WR1 production.',
    gameId: 'game_2',
  },
  // NBA picks
  {
    id: 'pick_4',
    sport: 'NBA',
    sportEmoji: '🏀',
    playerName: 'LeBron James',
    team: 'LA Lakers',
    position: 'SF',
    statType: 'Points',
    line: 24.5,
    grade: 'B',
    confidence: 76,
    recommendation: 'OVER',
    edgeSummary: 'Favorable matchup vs. a weak paint defense.',
    gameInfo: 'Lakers @ Celtics · 7:30 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -110 },
      { book: 'DraftKings', odds: -108, isBest: true },
      { book: 'BetMGM', odds: -112 },
    ],
    keyFactors: [
      'LeBron averaging 27.3 pts in last 5 games',
      'Celtics allow 4th-most paint points',
      'AD questionable — LeBron usage rate climbs',
    ],
    risks: [
      'Back-to-back game fatigue',
      'Celtics may double team in 4th quarter',
    ],
    trendOverCount: 7,
    trendTotal: 10,
    trendAvg: 26.8,
    aiAnalysis: 'LeBron James has been on a scoring tear, averaging 27.3 points over his last 5 games. With Anthony Davis listed as questionable, LeBron\'s usage rate climbs to an elite 34%. The Celtics allow the 4th-most paint points in the NBA, which is LeBron\'s bread and butter.',
    gameId: 'game_4',
  },
  {
    id: 'pick_5',
    sport: 'NBA',
    sportEmoji: '🏀',
    playerName: 'Jayson Tatum',
    team: 'BOS Celtics',
    position: 'SF',
    statType: 'Rebounds',
    line: 8.5,
    grade: 'A',
    confidence: 85,
    recommendation: 'OVER',
    edgeSummary: 'Tatum has been a glass-cleaner recently.',
    gameInfo: 'Lakers @ Celtics · 7:30 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -120 },
      { book: 'DraftKings', odds: -115, isBest: true },
      { book: 'BetMGM', odds: -125 },
    ],
    keyFactors: [
      'Tatum averaging 10.2 rebounds in last 8 games',
      'Lakers rank bottom-5 in defensive rebounding rate',
      'Tatum playing 37+ minutes consistently',
    ],
    risks: [
      'Kristaps Porzingis return may reduce rebounding opportunities',
    ],
    trendOverCount: 8,
    trendTotal: 10,
    trendAvg: 9.8,
    aiAnalysis: 'Jayson Tatum has been an aggressive rebounder recently, averaging 10.2 boards over his last 8 games. The Lakers rank in the bottom-5 for defensive rebounding rate, creating plenty of opportunities on the glass.',
    gameId: 'game_4',
  },
  {
    id: 'pick_6',
    sport: 'NBA',
    sportEmoji: '🏀',
    playerName: 'Luka Doncic',
    team: 'DAL Mavericks',
    position: 'PG',
    statType: 'Assists',
    line: 8.5,
    grade: 'D',
    confidence: 41,
    recommendation: 'UNDER',
    edgeSummary: 'Doncic more focused on scoring vs. weak perimeter D.',
    gameInfo: 'Mavericks @ Warriors · 10:00 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -105 },
      { book: 'DraftKings', odds: -110 },
      { book: 'BetMGM', odds: -102, isBest: true },
    ],
    keyFactors: [
      'Warriors weak perimeter defense invites scoring',
      'Doncic under 8.5 assists in 6/10 games as scoring leader',
    ],
    risks: [
      'Doncic can pile up assists in blowouts',
      'Warriors zone could lead to kick-out assists',
    ],
    trendOverCount: 4,
    trendTotal: 10,
    trendAvg: 7.9,
    aiAnalysis: 'When Luka Doncic is in scoring mode, his assist numbers tend to dip. Against weak perimeter defenses like the Warriors, he has historically taken more shots himself.',
    gameId: 'game_5',
  },
  // MLB picks
  {
    id: 'pick_7',
    sport: 'MLB',
    sportEmoji: '⚾',
    playerName: 'Shohei Ohtani',
    team: 'LA Dodgers',
    position: 'DH',
    statType: 'Total Bases',
    line: 1.5,
    grade: 'A',
    confidence: 88,
    recommendation: 'OVER',
    edgeSummary: 'Elite power hitter vs. struggling RHP.',
    gameInfo: 'Dodgers @ Padres · 9:40 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -135 },
      { book: 'DraftKings', odds: -130, isBest: true },
      { book: 'BetMGM', odds: -140 },
    ],
    keyFactors: [
      'Ohtani 9/12 OVER 1.5 total bases vs. RHP this month',
      'Opposing pitcher has 5.80 ERA in last 4 starts',
      'Ohtani hitting .380 with power at Petco Park',
    ],
    risks: [
      'Padres bullpen is elite if starter exits early',
    ],
    trendOverCount: 9,
    trendTotal: 12,
    trendAvg: 2.4,
    aiAnalysis: 'Shohei Ohtani has been crushing right-handed pitching, going over 1.5 total bases in 9 of his last 12 games against RHP. The opposing starter has a 5.80 ERA in his last 4 outings, and Ohtani is hitting .380 with extra-base power at Petco Park.',
    gameId: 'game_7',
  },
  {
    id: 'pick_8',
    sport: 'MLB',
    sportEmoji: '⚾',
    playerName: 'Aaron Judge',
    team: 'NY Yankees',
    position: 'OF',
    statType: 'Home Runs',
    line: 0.5,
    grade: 'B',
    confidence: 71,
    recommendation: 'OVER',
    edgeSummary: 'Judge has homered in 4 of last 6 vs. LHP.',
    gameInfo: 'Yankees @ Red Sox · 7:10 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: +140 },
      { book: 'DraftKings', odds: +145, isBest: true },
      { book: 'BetMGM', odds: +135 },
    ],
    keyFactors: [
      'Judge has 4 HRs in last 6 games vs. LHP',
      'Fenway Park short porch in right field',
      'Judge OPS .950+ vs. lefties this season',
    ],
    risks: [
      'Red Sox LHP has held sluggers in recent outings',
      'Wind blowing in from right field today',
    ],
    trendOverCount: 4,
    trendTotal: 6,
    trendAvg: 0.67,
    aiAnalysis: 'Aaron Judge has been locked in against left-handed pitching, homering in 4 of his last 6 games against LHP. Playing at Fenway with its short porch in right field adds an extra dimension.',
    gameId: 'game_8',
  },
  {
    id: 'pick_9',
    sport: 'MLB',
    sportEmoji: '⚾',
    playerName: 'Gerrit Cole',
    team: 'NY Yankees',
    position: 'SP',
    statType: 'Strikeouts',
    line: 7.5,
    grade: 'C',
    confidence: 58,
    recommendation: 'OVER',
    edgeSummary: 'High-K matchup but recent workload concerns.',
    gameInfo: 'Yankees @ Red Sox · 7:10 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -105 },
      { book: 'DraftKings', odds: +100, isBest: true },
      { book: 'BetMGM', odds: -110 },
    ],
    keyFactors: [
      'Red Sox strike out at 5th-highest rate in AL',
      'Cole averaging 8.2 K/9 this season',
    ],
    risks: [
      'Cole on short rest — may be limited to 5 innings',
      'Red Sox lineup has been more patient recently',
    ],
    trendOverCount: 5,
    trendTotal: 10,
    trendAvg: 7.8,
    aiAnalysis: 'Gerrit Cole faces a Red Sox lineup that strikes out at the 5th-highest rate in the American League. However, Cole is on short rest and may be limited in his pitch count.',
    gameId: 'game_8',
  },
  // NCAAF picks
  {
    id: 'pick_10',
    sport: 'NCAAF',
    sportEmoji: '🏈',
    playerName: 'Carson Beck',
    team: 'Georgia',
    position: 'QB',
    statType: 'Passing Yards',
    line: 245.5,
    grade: 'B',
    confidence: 74,
    recommendation: 'OVER',
    edgeSummary: 'Georgia likely to air it out in shootout potential.',
    gameInfo: 'Georgia vs. Alabama · 3:30 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -110 },
      { book: 'DraftKings', odds: -105, isBest: true },
      { book: 'BetMGM', odds: -115 },
    ],
    keyFactors: [
      'Beck averaging 280+ passing yards vs. top-25 teams',
      'Game total set at 52.5 — shootout expected',
      'Alabama secondary depleted by injuries',
    ],
    risks: [
      'Georgia may lean on run game if they build early lead',
    ],
    trendOverCount: 6,
    trendTotal: 8,
    trendAvg: 268.3,
    aiAnalysis: 'Carson Beck has excelled in big games this season, averaging over 280 passing yards against top-25 opponents. The game total of 52.5 suggests oddsmakers expect a high-scoring affair, and Alabama\'s secondary has been depleted by injuries.',
    gameId: 'game_10',
  },
  {
    id: 'pick_11',
    sport: 'NCAAF',
    sportEmoji: '🏈',
    playerName: 'Jalen Milroe',
    team: 'Alabama',
    position: 'QB',
    statType: 'Rushing Yards',
    line: 45.5,
    grade: 'A',
    confidence: 83,
    recommendation: 'OVER',
    edgeSummary: 'Milroe is a dynamic dual-threat in big games.',
    gameInfo: 'Georgia vs. Alabama · 3:30 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -115 },
      { book: 'DraftKings', odds: -110, isBest: true },
    ],
    keyFactors: [
      'Milroe 7/8 games OVER 45.5 rush yards this season',
      'Georgia defense vulnerable to mobile QBs',
      'Designed QB runs a key part of Alabama\'s gameplan',
    ],
    risks: [
      'Georgia\'s pass rush may force quick throws instead of runs',
    ],
    trendOverCount: 7,
    trendTotal: 8,
    trendAvg: 62.4,
    aiAnalysis: 'Jalen Milroe has been one of the most dynamic rushing QBs in college football. He has gone over 45.5 rushing yards in 7 of 8 games this season, and Georgia\'s defense has shown vulnerability to mobile quarterbacks.',
    gameId: 'game_10',
  },
  {
    id: 'pick_12',
    sport: 'NCAAF',
    sportEmoji: '🏈',
    playerName: 'Ollie Gordon II',
    team: 'Oklahoma St',
    position: 'RB',
    statType: 'Rushing Yards',
    line: 105.5,
    grade: 'F',
    confidence: 28,
    recommendation: 'UNDER',
    edgeSummary: 'Facing the #1 rush defense in the Big 12.',
    gameInfo: 'Oklahoma St @ Texas · 12:00 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -110 },
      { book: 'DraftKings', odds: -108, isBest: true },
    ],
    keyFactors: [
      'Texas #1 rush defense in Big 12 (78 avg allowed)',
      'Oklahoma St likely trailing — abandoning run',
    ],
    risks: [
      'Gordon is a bellcow — guaranteed 20+ carries',
      'Texas may rest starters if blowout',
    ],
    trendOverCount: 3,
    trendTotal: 10,
    trendAvg: 88.2,
    aiAnalysis: 'Ollie Gordon II faces his toughest test of the season against the #1 rush defense in the Big 12. Texas allows just 78 rushing yards per game, and Oklahoma State is expected to trail, limiting rushing volume.',
    gameId: 'game_11',
  },
  // NCAAB picks
  {
    id: 'pick_13',
    sport: 'NCAAB',
    sportEmoji: '🏀',
    playerName: 'Zach Edey',
    team: 'Purdue',
    position: 'C',
    statType: 'Points',
    line: 22.5,
    grade: 'A',
    confidence: 89,
    recommendation: 'OVER',
    edgeSummary: 'Dominant big man vs. undersized opponent.',
    gameInfo: 'Purdue vs. UConn · 6:00 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -125 },
      { book: 'DraftKings', odds: -120, isBest: true },
      { book: 'BetMGM', odds: -130 },
    ],
    keyFactors: [
      'Edey averaging 25.1 PPG in last 10 games',
      'UConn lacks a true rim protector at his size',
      'Purdue feeds Edey 30+ touches per game',
    ],
    risks: [
      'UConn may use double-teams to force ball out of his hands',
    ],
    trendOverCount: 8,
    trendTotal: 10,
    trendAvg: 25.4,
    aiAnalysis: 'Zach Edey has been virtually unstoppable, averaging 25.1 points over his last 10 games. UConn lacks a true rim protector who can match his size, and Purdue consistently feeds him the ball in the post.',
    gameId: 'game_13',
  },
  {
    id: 'pick_14',
    sport: 'NCAAB',
    sportEmoji: '🏀',
    playerName: 'RJ Davis',
    team: 'UNC',
    position: 'PG',
    statType: 'Points + Assists',
    line: 24.5,
    grade: 'B',
    confidence: 72,
    recommendation: 'OVER',
    edgeSummary: 'Davis thrives in high-usage spots.',
    gameInfo: 'UNC vs. Duke · 8:00 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -108 },
      { book: 'DraftKings', odds: -105, isBest: true },
    ],
    keyFactors: [
      'Davis averaging 26.8 PRA in rivalry games',
      'Duke allows 3rd-most points to PGs in ACC',
    ],
    risks: [
      'Rivalry games can be unpredictable',
      'Davis may settle for jumpers',
    ],
    trendOverCount: 6,
    trendTotal: 10,
    trendAvg: 25.9,
    aiAnalysis: 'RJ Davis elevates his game in rivalry situations, averaging 26.8 points + assists in rivalry matchups. Duke allows the 3rd-most points to point guards in the ACC this season.',
    gameId: 'game_14',
  },
  {
    id: 'pick_15',
    sport: 'NCAAB',
    sportEmoji: '🏀',
    playerName: 'Kyle Filipowski',
    team: 'Duke',
    position: 'PF',
    statType: 'Rebounds',
    line: 8.5,
    grade: 'D',
    confidence: 38,
    recommendation: 'UNDER',
    edgeSummary: 'UNC dominates the glass — tough spot for boards.',
    gameInfo: 'UNC vs. Duke · 8:00 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -105 },
      { book: 'DraftKings', odds: -102, isBest: true },
    ],
    keyFactors: [
      'UNC #2 in offensive rebounding rate',
      'Filipowski under 8.5 in 6/10 vs. top rebounding teams',
    ],
    risks: [
      'Filipowski is Duke\'s primary rebounder — high volume',
    ],
    trendOverCount: 4,
    trendTotal: 10,
    trendAvg: 7.6,
    aiAnalysis: 'Kyle Filipowski faces a UNC team that ranks #2 in offensive rebounding rate, which limits defensive rebounding opportunities. He has gone under 8.5 rebounds in 6 of 10 games against top rebounding teams.',
    gameId: 'game_14',
  },
  {
    id: 'pick_16',
    sport: 'NFL',
    sportEmoji: '🏈',
    playerName: 'Travis Kelce',
    team: 'KC Chiefs',
    position: 'TE',
    statType: 'Receptions',
    line: 5.5,
    grade: 'B',
    confidence: 75,
    recommendation: 'OVER',
    edgeSummary: 'Kelce is Mahomes\' safety valve in big games.',
    gameInfo: 'Chiefs @ Ravens · 8:20 PM ET',
    bookOdds: [
      { book: 'FanDuel', odds: -115 },
      { book: 'DraftKings', odds: -110, isBest: true },
    ],
    keyFactors: [
      'Kelce 9/10 OVER 5.5 receptions in prime-time',
      'Ravens LBs struggle in coverage vs. TEs',
    ],
    risks: [
      'Kelce snap count may decrease late in game',
    ],
    trendOverCount: 9,
    trendTotal: 10,
    trendAvg: 7.2,
    aiAnalysis: 'Travis Kelce has been automatic in prime-time games, going over 5.5 receptions in 9 of 10 such games. The Ravens linebackers have struggled in coverage against tight ends all season.',
    gameId: 'game_1',
  },
];

export const MOCK_GAMES: Game[] = [
  // NFL
  { id: 'game_1', sport: 'NFL', sportEmoji: '🏈', homeTeam: 'Baltimore Ravens', awayTeam: 'Kansas City Chiefs', gameTime: '8:20 PM ET', status: 'scheduled', spread: 'BAL -3', overUnder: 49.5, venue: 'M&T Bank Stadium' },
  { id: 'game_2', sport: 'NFL', sportEmoji: '🏈', homeTeam: 'Buffalo Bills', awayTeam: 'Miami Dolphins', gameTime: '1:00 PM ET', status: 'scheduled', spread: 'BUF -6.5', overUnder: 48, venue: 'Highmark Stadium' },
  { id: 'game_3', sport: 'NFL', sportEmoji: '🏈', homeTeam: 'Dallas Cowboys', awayTeam: 'Philadelphia Eagles', gameTime: '4:25 PM ET', status: 'scheduled', spread: 'PHI -2.5', overUnder: 45.5, venue: 'AT&T Stadium' },
  // NBA
  { id: 'game_4', sport: 'NBA', sportEmoji: '🏀', homeTeam: 'Boston Celtics', awayTeam: 'Los Angeles Lakers', gameTime: '7:30 PM ET', status: 'scheduled', spread: 'BOS -5', overUnder: 224.5, venue: 'TD Garden' },
  { id: 'game_5', sport: 'NBA', sportEmoji: '🏀', homeTeam: 'Golden State Warriors', awayTeam: 'Dallas Mavericks', gameTime: '10:00 PM ET', status: 'scheduled', spread: 'GSW -3.5', overUnder: 230, venue: 'Chase Center' },
  { id: 'game_6', sport: 'NBA', sportEmoji: '🏀', homeTeam: 'Denver Nuggets', awayTeam: 'Phoenix Suns', gameTime: '9:00 PM ET', status: 'scheduled', spread: 'DEN -4', overUnder: 226, venue: 'Ball Arena' },
  // MLB
  { id: 'game_7', sport: 'MLB', sportEmoji: '⚾', homeTeam: 'San Diego Padres', awayTeam: 'Los Angeles Dodgers', gameTime: '9:40 PM ET', status: 'scheduled', spread: 'LAD -145', overUnder: 8.5, venue: 'Petco Park' },
  { id: 'game_8', sport: 'MLB', sportEmoji: '⚾', homeTeam: 'Boston Red Sox', awayTeam: 'New York Yankees', gameTime: '7:10 PM ET', status: 'scheduled', spread: 'NYY -130', overUnder: 9, venue: 'Fenway Park' },
  { id: 'game_9', sport: 'MLB', sportEmoji: '⚾', homeTeam: 'Houston Astros', awayTeam: 'Texas Rangers', gameTime: '8:10 PM ET', status: 'scheduled', spread: 'HOU -150', overUnder: 8, venue: 'Minute Maid Park' },
  // NCAAF
  { id: 'game_10', sport: 'NCAAF', sportEmoji: '🏈', homeTeam: 'Alabama', awayTeam: 'Georgia', gameTime: '3:30 PM ET', status: 'scheduled', spread: 'UGA -3', overUnder: 52.5, venue: 'Bryant-Denny Stadium' },
  { id: 'game_11', sport: 'NCAAF', sportEmoji: '🏈', homeTeam: 'Texas', awayTeam: 'Oklahoma State', gameTime: '12:00 PM ET', status: 'scheduled', spread: 'TEX -17.5', overUnder: 55, venue: 'Darrell K Royal Stadium' },
  // NCAAB
  { id: 'game_13', sport: 'NCAAB', sportEmoji: '🏀', homeTeam: 'UConn', awayTeam: 'Purdue', gameTime: '6:00 PM ET', status: 'scheduled', spread: 'UCONN -2', overUnder: 145, venue: 'Gampel Pavilion' },
  { id: 'game_14', sport: 'NCAAB', sportEmoji: '🏀', homeTeam: 'Duke', awayTeam: 'UNC', gameTime: '8:00 PM ET', status: 'scheduled', spread: 'DUKE -1.5', overUnder: 152, venue: 'Cameron Indoor Stadium' },
];

export const MOCK_PROPS: PlayerProp[] = MOCK_PICKS.map((pick) => ({
  id: `prop_${pick.id}`,
  sport: pick.sport,
  sportEmoji: pick.sportEmoji,
  playerName: pick.playerName,
  team: pick.team,
  position: pick.position,
  statType: pick.statType,
  line: pick.line,
  grade: pick.grade,
  confidence: pick.confidence,
  recommendation: pick.recommendation,
  edgeSummary: pick.edgeSummary,
  gameInfo: pick.gameInfo,
  gameId: pick.gameId ?? '',
  bookOdds: pick.bookOdds,
  keyFactors: pick.keyFactors,
  risks: pick.risks,
  trendOverCount: pick.trendOverCount,
  trendTotal: pick.trendTotal,
  trendAvg: pick.trendAvg,
  aiAnalysis: pick.aiAnalysis,
}));

// Add a few extra props
const EXTRA_PROPS: PlayerProp[] = [
  {
    id: 'prop_extra_1',
    sport: 'NBA',
    sportEmoji: '🏀',
    playerName: 'Stephen Curry',
    team: 'GS Warriors',
    position: 'PG',
    statType: '3-Pointers Made',
    line: 3.5,
    grade: 'B',
    confidence: 73,
    recommendation: 'OVER',
    edgeSummary: 'Curry shooting lights out from deep recently.',
    gameInfo: 'Mavericks @ Warriors · 10:00 PM ET',
    gameId: 'game_5',
    bookOdds: [
      { book: 'FanDuel', odds: -115 },
      { book: 'DraftKings', odds: -110, isBest: true },
    ],
    keyFactors: ['Curry 7/10 OVER 3.5 threes in last 10', 'Mavericks allow most 3PM to PGs'],
    risks: ['Curry may rest in 4th if blowout'],
    trendOverCount: 7,
    trendTotal: 10,
    trendAvg: 4.2,
    aiAnalysis: 'Stephen Curry has been on a three-point shooting tear, hitting over 3.5 threes in 7 of his last 10 games. The Mavericks allow the most three-pointers to opposing point guards.',
  },
  {
    id: 'prop_extra_2',
    sport: 'NFL',
    sportEmoji: '🏈',
    playerName: 'Josh Allen',
    team: 'BUF Bills',
    position: 'QB',
    statType: 'Pass + Rush Yards',
    line: 310.5,
    grade: 'A',
    confidence: 86,
    recommendation: 'OVER',
    edgeSummary: 'Allen\'s dual-threat ability makes this a lock.',
    gameInfo: 'Dolphins @ Bills · 1:00 PM ET',
    gameId: 'game_2',
    bookOdds: [
      { book: 'FanDuel', odds: -120 },
      { book: 'DraftKings', odds: -115, isBest: true },
    ],
    keyFactors: ['Allen averaging 325 total yards at home', 'Dolphins defense depleted by injuries', 'Allen 9/10 OVER 310.5 total yards at home'],
    risks: ['Bills may rest Allen late if blowout'],
    trendOverCount: 9,
    trendTotal: 10,
    trendAvg: 332.5,
    aiAnalysis: 'Josh Allen has been dominant at home this season, averaging 325 total yards (pass + rush) per game at Highmark Stadium. The Dolphins defense has been decimated by injuries.',
  },
  {
    id: 'prop_extra_3',
    sport: 'MLB',
    sportEmoji: '⚾',
    playerName: 'Mookie Betts',
    team: 'LA Dodgers',
    position: 'SS',
    statType: 'Hits + Runs + RBIs',
    line: 2.5,
    grade: 'C',
    confidence: 59,
    recommendation: 'OVER',
    edgeSummary: 'Betts has been a multi-category contributor.',
    gameInfo: 'Dodgers @ Padres · 9:40 PM ET',
    gameId: 'game_7',
    bookOdds: [
      { book: 'FanDuel', odds: -105 },
      { book: 'DraftKings', odds: +100, isBest: true },
    ],
    keyFactors: ['Betts 6/10 OVER 2.5 H+R+RBI', 'Batting .320 in away games this month'],
    risks: ['Padres starter has held Betts to .200 career'],
    trendOverCount: 6,
    trendTotal: 10,
    trendAvg: 2.8,
    aiAnalysis: 'Mookie Betts has been a consistent multi-category contributor, going over 2.5 H+R+RBI in 6 of his last 10 games. He is batting .320 in away games this month.',
  },
  {
    id: 'prop_extra_4',
    sport: 'NCAAF',
    sportEmoji: '🏈',
    playerName: 'Quinn Ewers',
    team: 'Texas',
    position: 'QB',
    statType: 'Passing TDs',
    line: 2.5,
    grade: 'B',
    confidence: 70,
    recommendation: 'OVER',
    edgeSummary: 'Ewers feasting on weak secondary.',
    gameInfo: 'Oklahoma St @ Texas · 12:00 PM ET',
    gameId: 'game_11',
    bookOdds: [
      { book: 'FanDuel', odds: +105 },
      { book: 'DraftKings', odds: +110, isBest: true },
    ],
    keyFactors: ['Ewers 5/7 OVER 2.5 TDs at home', 'OK State ranks last in Big 12 pass D'],
    risks: ['Texas may pull starters early in blowout'],
    trendOverCount: 5,
    trendTotal: 7,
    trendAvg: 2.9,
    aiAnalysis: 'Quinn Ewers has been efficient at home, throwing 3+ touchdowns in 5 of 7 home games. Oklahoma State ranks last in the Big 12 in pass defense.',
  },
];

MOCK_PROPS.push(...EXTRA_PROPS);

export const MOCK_SAVED_PICKS: SavedPick[] = [
  { id: 'saved_1', playerName: 'Patrick Mahomes', team: 'KC Chiefs', statType: 'Passing Yards', line: 275.5, recommendation: 'OVER', grade: 'A', confidence: 90, result: 'WIN', date: '2026-09-07', sport: 'NFL' },
  { id: 'saved_2', playerName: 'LeBron James', team: 'LA Lakers', statType: 'Points', line: 25.5, recommendation: 'OVER', grade: 'B', confidence: 74, result: 'WIN', date: '2026-09-07', sport: 'NBA' },
  { id: 'saved_3', playerName: 'Shohei Ohtani', team: 'LA Dodgers', statType: 'Total Bases', line: 2.5, recommendation: 'OVER', grade: 'A', confidence: 85, result: 'LOSS', date: '2026-09-06', sport: 'MLB' },
  { id: 'saved_4', playerName: 'Jalen Hurts', team: 'PHI Eagles', statType: 'Rush Yards', line: 35.5, recommendation: 'OVER', grade: 'C', confidence: 60, result: 'PUSH', date: '2026-09-06', sport: 'NFL' },
  { id: 'saved_5', playerName: 'Jayson Tatum', team: 'BOS Celtics', statType: 'Rebounds', line: 8.5, recommendation: 'OVER', grade: 'A', confidence: 82, result: 'PENDING', date: '2026-09-09', sport: 'NBA' },
];

export const MOCK_ALERTS: Alert[] = [
  { id: 'alert_1', type: 'line_movement', title: 'Line Movement — Mahomes Passing', description: 'Patrick Mahomes Passing Yards line moved from 280.5 to 285.5 (+5). Sharp money detected on OVER.', timestamp: '12 min ago', sport: 'NFL', sportEmoji: '🏈' },
  { id: 'alert_2', type: 'injury', title: 'Injury Alert — Anthony Davis', description: 'Anthony Davis (LA Lakers) listed as QUESTIONABLE with knee soreness. Monitor status before tip-off.', timestamp: '45 min ago', sport: 'NBA', sportEmoji: '🏀' },
  { id: 'alert_3', type: 'line_movement', title: 'Line Movement — UGA/BAMA Total', description: 'Georgia vs Alabama game total moved from 51 to 52.5. Action on the over.', timestamp: '2 hrs ago', sport: 'NCAAF', sportEmoji: '🏈' },
];
